# Generated by Django 5.2.9 on 2025-12-15 07:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_comment_gold_coins_alter_communitypost_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPostQueueEntry',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('flagged', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='communitypost',
            name='content_json',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communitypost',
            name='coverImg',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communitypost',
            name='is_flagged',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communitypost',
            name='post_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
