# Generated by Django 5.2.9 on 2025-12-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_communitypostqueueentry_communitypost_content_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
