# Generated by Django 5.2.9 on 2025-12-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_communitypost_is_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_img_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
