# Generated by Django 5.2.9 on 2025-12-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_like_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='dislike_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
