# Generated by Django 5.2.9 on 2026-01-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userprofile_goal_userprofile_share_profile_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='pendingModeration',
            field=models.BooleanField(default=True),
        ),
    ]
