# Generated by Django 5.2.9 on 2026-01-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_communitypost_pendingmoderation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='is_flagged',
            field=models.BooleanField(default=True),
        ),
    ]
